# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/London"
    labels:
      - "npm"
      - "dependencies"
      
 - package-ecosystem: "github-actions"
   directory: "/"
   schedule:
     interval: "weekly"
     time: "09:00"
     timezone: "Europe/London"
   labels:
     - "gh-actions"
     - "dependencies"
