packages:
  - 'packages/*'
  - 'app/**'
overrides:
  protobufjs: 8.3.0
  tmp: 0.2.6
minimumReleaseAge: 10080
autoInstallPeers: true
blockExoticSubdeps: true
linkWorkspacePackages: true
optimisticRepeatInstall: false
preferWorkspacePackages: true
saveWorkspaceProtocol: 'rolling'
strictPeerDependencies: false
trustPolicy: 'off'
allowBuilds:
  '@pulumi/command': true
  '@pulumi/std': true
  esbuild: false
  protobufjs: false
  unrs-resolver: false
