import { ZeroTrustAccessApplicationConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-application'
import { ZeroTrustAccessShortLivedCertificateConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-short-lived-certificate'
import { ZeroTrustAccessCustomPageConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-custom-page'
import { ZeroTrustAccessGroupConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-group'
import { ZeroTrustAccessIdentityProviderConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-identity-provider'
import { ZeroTrustAccessMtlsCertificateConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-mtls-certificate'
import { ZeroTrustOrganizationConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-organization'
import { ZeroTrustAccessPolicyConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-policy'
import { AccessRuleConfig } from '@cdktf/provider-cloudflare/lib/access-rule'
import { ZeroTrustAccessServiceTokenConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-service-token'
import { ZeroTrustAccessTagConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-tag'

export interface ZeroTrustAccessApplicationProps extends ZeroTrustAccessApplicationConfig {}
export interface ZeroTrustAccessShortLivedCertificateProps extends ZeroTrustAccessShortLivedCertificateConfig {}
export interface ZeroTrustAccessCustomPageProps extends ZeroTrustAccessCustomPageConfig {}
export interface ZeroTrustAccessGroupProps extends ZeroTrustAccessGroupConfig {}
export interface ZeroTrustAccessIdentityProviderProps extends ZeroTrustAccessIdentityProviderConfig {}
export interface ZeroTrustAccessMtlsCertificateProps extends ZeroTrustAccessMtlsCertificateConfig {}
export interface ZeroTrustOrganizationProps extends ZeroTrustOrganizationConfig {}
export interface ZeroTrustAccessPolicyProps extends ZeroTrustAccessPolicyConfig {}
export interface AccessRuleProps extends AccessRuleConfig {}
export interface ZeroTrustAccessServiceTokenProps extends ZeroTrustAccessServiceTokenConfig {}
export interface ZeroTrustAccessTagProps extends ZeroTrustAccessTagConfig {}
