import { AccessRuleConfig } from '@cdktf/provider-cloudflare/lib/access-rule/index.js'
import { ZeroTrustAccessApplicationConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-application/index.js'
import { ZeroTrustAccessCustomPageConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-custom-page/index.js'
import { ZeroTrustAccessGroupConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-group/index.js'
import { ZeroTrustAccessIdentityProviderConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-identity-provider/index.js'
import { ZeroTrustAccessMtlsCertificateConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-mtls-certificate/index.js'
import { ZeroTrustAccessPolicyConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-policy/index.js'
import { ZeroTrustAccessServiceTokenConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-service-token/index.js'
import { ZeroTrustAccessShortLivedCertificateConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-short-lived-certificate/index.js'
import { ZeroTrustAccessTagConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-access-tag/index.js'
import { ZeroTrustOrganizationConfig } from '@cdktf/provider-cloudflare/lib/zero-trust-organization/index.js'

export interface ZeroTrustAccessApplicationProps extends ZeroTrustAccessApplicationConfig {}
export interface ZeroTrustAccessShortLivedCertificateProps extends ZeroTrustAccessShortLivedCertificateConfig {}
export interface ZeroTrustAccessCustomPageProps extends ZeroTrustAccessCustomPageConfig {}
export interface ZeroTrustAccessGroupProps extends ZeroTrustAccessGroupConfig {}
export interface ZeroTrustAccessIdentityProviderProps extends ZeroTrustAccessIdentityProviderConfig {}
export interface ZeroTrustAccessMtlsCertificateProps extends ZeroTrustAccessMtlsCertificateConfig {}
export interface ZeroTrustOrganizationProps extends ZeroTrustOrganizationConfig {}
export interface ZeroTrustAccessPolicyProps extends ZeroTrustAccessPolicyConfig {}
export interface AccessRuleProps extends AccessRuleConfig {}
export interface ZeroTrustAccessServiceTokenProps extends ZeroTrustAccessServiceTokenConfig {}
export interface ZeroTrustAccessTagProps extends ZeroTrustAccessTagConfig {}
