on:
  push:
    branches:
      - main

name: AWS Common Utilities Release Pipeline

env:
  name: AWS Common Utilities Release Pipeline
  GITHUB_PUBLISH_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  build:
    name: Build Package(s)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-
      - name: Cache Build Output
        uses: actions/cache@v2
        id: cache-build-output
        env:
          cache-name: cache-build-output
        with:
          path: dist
          key: ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-${{ hashFiles('build/**/*.js') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-
      - name: Cache Documentation
        uses: actions/cache@v2
        id: cache-docs
        env:
          cache-name: cache-docs
        with:
          path: docs
          key: ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-${{ hashFiles('docs/**/*.html') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-
      - name: Install Packages
        run: yarn install --frozen-lockfile
      - name: Build Packages
        run: yarn build
      - name: Validate Documentation
        run: yarn docs

  test:
    name: Test Package(s)
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs: [ build ]
    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-${{ hashFiles('build/**/*.js') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-
      - name: Install Packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Test Packages
        run: yarn validate
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: coverage/*.xml

  release:
    name: Release Package(s)
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs: [ build, test ]
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-
      - name: Cache Build Output
        uses: actions/cache@v2
        id: cache-build-output
        env:
          cache-name: cache-build-output
        with:
          path: dist
          key: ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-${{ hashFiles('build/**/*.js') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-
      - name: Cache Documentation
        uses: actions/cache@v2
        id: cache-docs
        env:
          cache-name: cache-docs
        with:
          path: docs
          key: ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-${{ hashFiles('docs/**/*.html') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-${{ env.cache-name }}-
      - name: Install Packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build Packages
        if: steps.cache-build-output.outputs.cache-hit != 'true'
        run: yarn build
      - name: Validate Documentation
        if: steps.cache-docs.outputs.cache-hit != 'true'
        run: yarn docs
      - name: Deploy Package(s)
        run: npm publish
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ env.GITHUB_PUBLISH_TOKEN }}
          publish_dir: ./docs
